from __future__ import annotations

from typing import TYPE_CHECKING, NamedTuple, Optional, Callable, List

from BaseClasses import ItemClassification, Location, CollectionState

from .regions import *
from .options import *
from . import items

if TYPE_CHECKING:
    from .world import OurAscentWorld


class OurAscentLocation(Location):
    game = "Our Ascent"

#def get_location_names_with_ids(location_names: list[str]) -> dict[str, int | None]:
#    return {location_name: LOCATION_NAME_TO_ID[location_name] for location_name in location_names}

def get_location_name_to_id() -> dict[str, int]:
    location_name_to_id = {location.name: location.code for location in get_11_locations(-1, None)}

    #location_name_to_id.update()
    return location_name_to_id

#def create_all_locations(world: OurAscentWorld) -> None:
#    create_regular_locations(world)
#    create_events(world)

#def create_regular_locations(world: OurAscentWorld) -> None:
#    main_menu = world.get_region("Main Menu")
#    FALLING_INTO_CHAOS_1 = world.get_region("1-1 Beginning-Right")
#    STAGE_11_REGION_2 = world.get_region("1-1 Beginning-Left")
#    STAGE_11_REGION_3 = world.get_region("1-1 Further Right")
#    STAGE_11_REGION_4 = world.get_region("1-1 Further Left")
#    STAGE_11_REGION_5 = world.get_region("1-1 Center")
#    STAGE_11_REGION_6 = world.get_region("1-1 Top")

class LocationData(NamedTuple):
    regions: str
    name: str
    code: int
    rule: Optional[Callable[[CollectionState], bool]] = None

def get_11_locations(player: int, options: OurAscentOptions | None) -> List[LocationData]:
    logic = OurAscentLogic(player, options)
    location_table: List[LocationData] = [
        #Glades Story 1 Enemies
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (1) Blue Slime", 1),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (1) Cute Pollen", 2),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (1) Fluff Ball", 3),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (1) Happy Flower", 4),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (10) Armapillar", 5),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (10) Darkluff", 6),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (10) Noxluff:", 7),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (10) Shrooma:", 8),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (25) Lunarfly", 9),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (25) R.ouch", 10),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (25) Tridentpupa", 11),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (40) Angrbee", 12),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (40) Angropper", 13),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (40) Angrot", 14),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (60) Firecada", 15),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (60) Firecarab", 16),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (60) Firent", 17),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (60) Firetick", 18),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (80) Angrspore", 19),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (80) Angrstrider", 20),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (80) Angrull", 21),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (80) Angrurker", 22),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (100) Attacker Slime", 23),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (100) Buffer Slime", 24),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (100) Caster Slime", 25),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (100) Debuffer Slime", 26),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (100) Defender Slime", 27),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (100) Healer Slime", 28),
        LocationData("FALLING_INTO_CHAOS_0", "1-1 Enemy - (100) Slime King (Boss)", 29),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (150) Corrupted Shell", 30),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (150) Killer Urchin", 31),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (150) Hermit Crabber", 32),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (250) Blue Draglug", 33),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (250) Corrupted Starfish", 34),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (250) Star n' Shell", 35),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (360) Jellyhead", 36),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (360) Lickitoad", 37),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (360) Shorsea", 38),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (490) Droozuna", 39),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (490) Manyfin", 40),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (490) Starthree", 41),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (700) Ambominaish", 42),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (700) Horntle", 43),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (700) Piranos", 44),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (700) Skullface", 45),
        LocationData("FALLING_INTO_CHAOS_2", "1-1 Enemy - (700) Fish Emperor (Boss)", 46),
        LocationData("FALLING_INTO_CHAOS_4", "1-1 Enemy - (1200) Imperiacrab", 47),
        LocationData("FALLING_INTO_CHAOS_4", "1-1 Enemy - (1200) Imperiobster", 48),
        LocationData("FALLING_INTO_CHAOS_4", "1-1 Enemy - (1200) Imperiatrider", 49),
        LocationData("FALLING_INTO_CHAOS_4", "1-1 Enemy - (1200) Imperiartle", 50),
        LocationData("FALLING_INTO_CHAOS_4", "1-1 Enemy - (1200) Crab Emperor (Boss)", 51),
        LocationData("FALLING_INTO_CHAOS_1", "1-1 Enemy - (70) Crabber", 52),
        LocationData("FALLING_INTO_CHAOS_1", "1-1 Enemy - (70) Rotund Toad", 53),
        LocationData("FALLING_INTO_CHAOS_1", "1-1 Enemy - (70) Spikestar", 54),
        LocationData("FALLING_INTO_CHAOS_1", "1-1 Enemy - (130) Fat Frog Bat", 55),
        LocationData("FALLING_INTO_CHAOS_1", "1-1 Enemy - (130) Octibaby", 56),
        LocationData("FALLING_INTO_CHAOS_1", "1-1 Enemy - (130) Purple Shelly", 57),
        LocationData("FALLING_INTO_CHAOS_1", "1-1 Enemy - (200) DragonflyX", 58),
        LocationData("FALLING_INTO_CHAOS_1", "1-1 Enemy - (200) DragonflyY", 59),
        LocationData("FALLING_INTO_CHAOS_1", "1-1 Enemy - (200) Evil Shrooma", 60),
        LocationData("FALLING_INTO_CHAOS_1", "1-1 Enemy - (200) Hauntree", 61),
        LocationData("FALLING_INTO_CHAOS_1", "1-1 Enemy - (200) Stingoth (Boss)", 62),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (290) Weed Cannon", 63),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (290) PPPELICAN!!!", 64),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (290) Tortoad", 65),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (370) Rabbandit", 66),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (370) Rabbarcher", 67),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (370) Rabbight", 68),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (444) Drink!", 69),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (444) Loot!", 70),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (444) Throw", 71),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (500) Sword Angrant", 72),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (500) Archer Ant", 73),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (500) Hell Mantis", 74),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (500) Sickle Mantis", 75),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (500) Sword Ant", 76),
        LocationData("FALLING_INTO_CHAOS_3", "1-1 Enemy - (500) Mothapillar (Boss)", 77),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (580) Berserker Ant", 78),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (580) Mage Ant", 79),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (580) Protector Ant", 80),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (670) Archer Goblin", 81),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (670) Grunt Goblin", 82),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (670) Mage Goblin", 83),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (670) Raider Goblin", 84),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (670) Elite Goblin", 85),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (888) Hide!", 86),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (888) Open!", 87),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (888) Wear!", 88),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (1111) Close!", 89),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (1111) Hi!", 90),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (1111) Look!", 91),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (1414) Fear!", 92),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (1414) Fill!", 93),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (1414) Kill!", 94),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (1300) Parapillar", 95),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (1300) Serrant", 96),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (1300) Spidow", 97),
        LocationData("FALLING_INTO_CHAOS_5", "1-1 Enemy - (1300) Queen Spidow (Boss)", 98),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (1600) Bucket Jellyfish", 99),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (1600) Mega Octo Mind", 100),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (1600) SharkNATO", 101),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (1600) Voxai", 102),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (1900) BIG BAT", 103),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (1900) BIG CROW", 104),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (1900) BIG SCORP", 105),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (2222) Plunder!", 106),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (2222) Shoot!", 107),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (2222) Slice!", 108),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (2525) Defend!", 109),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (2525) Die!", 110),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (2525) Read!", 111),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (3000) Angranda", 112),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (3000) Angrdeer", 113),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (3000) Angree", 114),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (3000) Angrlower", 115),
        LocationData("FALLING_INTO_CHAOS_6", "1-1 Enemy - (3000) Anground (Boss)", 116),
        LocationData("FALLING_INTO_CHAOS_7", "1-1 Enemy - (3250) Axe Orc", 117),
        LocationData("FALLING_INTO_CHAOS_7", "1-1 Enemy - (3750) Sword Orc", 118),
        LocationData("FALLING_INTO_CHAOS_7", "1-1 Enemy - (3838) Archer Orc", 119),
        LocationData("FALLING_INTO_CHAOS_7", "1-1 Enemy - (3838) Mimic! (Boss)", 120),
        LocationData("FALLING_INTO_CHAOS_7", "1-1 Enemy - (4250) Warlock Orc", 121),
        LocationData("FALLING_INTO_CHAOS_7", "1-1 Enemy - (5000) Hog Rider!!!", 122),
        LocationData("FALLING_INTO_CHAOS_7", "1-1 Enemy - (5000) El Goblino (Boss)", 123),
        LocationData("FALLING_INTO_CHAOS_8", "1-1 Enemy - (6000) Baked Snake", 124),
        LocationData("FALLING_INTO_CHAOS_8", "1-1 Enemy - (6000) Ice Mantis", 125),
        LocationData("FALLING_INTO_CHAOS_8", "1-1 Enemy - (6000) Harrowed Hydra", 126),
        LocationData("FALLING_INTO_CHAOS_8", "1-1 Enemy - (7500) Hypo Ice Mantis", 127),
        LocationData("FALLING_INTO_CHAOS_8", "1-1 Enemy - (7500) Bothered Bidra", 128),
        LocationData("FALLING_INTO_CHAOS_8", "1-1 Enemy - (7500) Tyrannical Rex", 129),
        LocationData("FALLING_INTO_CHAOS_8", "1-1 Enemy - (10k R) Troubled Tridra", 130),
        LocationData("FALLING_INTO_CHAOS_8", "1-1 Enemy - (10k R) Flame Wolf", 131),
        LocationData("FALLING_INTO_CHAOS_8", "1-1 Enemy - (10k R) Jeweled Bear", 132),
        LocationData("FALLING_INTO_CHAOS_8", "1-1 Enemy - (10k R) Fairy Zephyria (Boss)", 133),
        LocationData("FALLING_INTO_CHAOS_8", "1-1 Enemy - (10k L) Butteragonfly", 134),
        LocationData("FALLING_INTO_CHAOS_8", "1-1 Enemy - (10k L) Locuswarm", 135),
        LocationData("FALLING_INTO_CHAOS_8", "1-1 Enemy - (10k L) Parapede", 136),
        LocationData("FALLING_INTO_CHAOS_8", "1-1 Enemy - (10k L) Fairy Fillia (Boss)", 137),

        #Apolonia's Chapter 1 Equipment
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Sword 1-1) Fragile Sword", 138),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Sword 1-2) Makeshift Hammer", 139),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Sword 1-3) Rusted Lance", 140),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Sword 1-4) Shabby Dagger", 141),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Sword 1-5) Bronze Axe", 142),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Sword 1-6) Simple Machete", 143),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Sword 1-7) Silver Hammer", 144),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Sword 1-8) Polished Lance", 145),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Sword 1-9) Tarnished Lance", 146),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Sword 1-10) El Goblino's Axe", 147),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Shield 1-1) Tiny Buckler", 148),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Shield 1-2) Big Wheel", 149),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Shield 1-3) Chipped Shield", 150),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Shield 1-4) Small Buckler", 151),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Shield 1-5) Heater Shield", 152),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Shield 1-6) Tri Shield", 153),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Shield 1-7) Polished Shield", 154),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Helmet 1-1) White Headband", 155),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Helmet 1-2) Copper Cap", 156),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Helmet 1-3) Bronze Helm", 157),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Helmet 1-4) Mail Helm", 158),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Helmet 1-5) Broken Barbute", 159),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Helmet 1-6) Reinforced Helm", 160),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Helmet 1-7) Bear Skin", 161),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Helmet 1-8) Shiny Barbute", 162),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Helmet 1-9) Mail Coif", 163),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Breastplate 1-1) Shabby Cuirass", 164),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Breastplate 1-2) Bronze Breastplate", 165),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Breastplate 1-3) Armored Tunic", 166),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Breastplate 1-4) Basic Chainmail", 167),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Breastplate 1-5) Reinforced Tunic", 168),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Breastplate 1-6) Tunic Chainmail", 169),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Breastplate 1-7) Heavy Armor", 170),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Breastplate 1-8) Adv. Chainmail", 171),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Breastplate 1-9) Iron Breastplate", 172),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Gloves 1-1) Basic Sleeves", 173),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Gloves 1-2) Simple Gloves", 174),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Gloves 1-3) Cushioned Sleeves", 175),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Gloves 1-4) Light Gloves", 176),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Gloves 1-5) Copper Gauntlets", 177),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Gloves 1-6) Large Gloves", 178),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Gloves 1-7) Fingerguard Bracers", 179),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Gloves 1-8) Chainmail Mitts", 180),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Gloves 1-9) Speedy Gloves", 181),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Boots 1-1) Open Sandals", 182),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Boots 1-2) Simple Loafers", 183),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Boots 1-3) Felt Shoes", 184),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Boots 1-4) Basic Greaves", 185),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Boots 1-5) Open Boots", 186),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Boots 1-6) Lined Boots", 187),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Boots 1-7) Bronze Sabatons", 188),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Boots 1-8) Fancy Boots", 189),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Boots 1-9) Plated Shoes", 190),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-1) Dull Ring 1", 191),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-1) Dull Ring 2", 192),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-1) Dull Ring 3", 193),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-2) Chipped Earring 1", 194),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-2) Chipped Earring 2", 195),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-2) Chipped Earring 3", 196),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-3) Death Ring I 1", 197),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-3) Death Ring I 2", 198),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-3) Death Ring I 3", 199),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-4) Shield Amulet 1", 200),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-4) Shield Amulet 2", 201),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-4) Shield Amulet 3", 202),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-5) Slim Double Band 1", 203),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-5) Slim Double Band 2", 204),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-5) Slim Double Band 3", 205),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-6) Fancy Ring 1", 206),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-6) Fancy Ring 2", 207),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-6) Fancy Ring 3", 208),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-7) Recovery Ring 1", 209),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-7) Recovery Ring 2", 210),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-7) Recovery Ring 3", 211),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-8) Coin Amulet 1", 212),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-8) Coin Amulet 2", 213),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-8) Coin Amulet 3", 214),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-9) Death Ring II 1", 215),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-9) Death Ring II 2", 216),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-9) Death Ring II 3", 217),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-10) Enchanted Ring 1", 218),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-10) Enchanted Ring 2", 219),
        LocationData("FALLING_INTO_CHAOS_1", "Apolonia Equipment - (Acc 1-10) Enchanted Ring 3", 220)
]