from .constants.ap_regions import *

story_id_to_name = {
    #Glades
    1: "1-1: Falling Into Chaos",
    2: "1-2: Rising To The Challenge",
    3: "1-3: Unleashing The Beast",
    4: "1-4: Hunting For Truth",
    5: "1-5: Lurking In The Shadows",

    #Oasis
    7: "2-1: Mirage Of Hope",
    8: "2-2: Sisters In Time"
}

character_id_to_name = {
    1: "Apolonia",
    2: "Stan",
    3: "Hina",
    4: "Lan",
    5: "Sibyl"
}

STORY_SELECT = "Main Menu"
STORY_SELECT_SUBREGIONS = [STORY_SELECT]
#Glades
FALLING_INTO_CHAOS = "1-1: Falling Into Chaos"
FALLING_INTO_CHAOS_SUBREGIONS = [FALLING_INTO_CHAOS_0, FALLING_INTO_CHAOS_1, FALLING_INTO_CHAOS_2, FALLING_INTO_CHAOS_3, FALLING_INTO_CHAOS_4, FALLING_INTO_CHAOS_5, FALLING_INTO_CHAOS_6, FALLING_INTO_CHAOS_7, FALLING_INTO_CHAOS_8]
RISING_TO_THE_CHALLENGE = "1-2: Rising To The Challenge"
RISING_TO_THE_CHALLENGE_SUBREGIONS = [RISING_TO_THE_CHALLENGE_0, RISING_TO_THE_CHALLENGE_1, RISING_TO_THE_CHALLENGE_2, RISING_TO_THE_CHALLENGE_3, RISING_TO_THE_CHALLENGE_4, RISING_TO_THE_CHALLENGE_5, RISING_TO_THE_CHALLENGE_6, RISING_TO_THE_CHALLENGE_7, RISING_TO_THE_CHALLENGE_8]
UNLEASHING_THE_BEAST = "1-3: Unleashing The Beast"
UNLEASHING_THE_BEAST_SUBREGIONS = [UNLEASHING_THE_BEAST_0, UNLEASHING_THE_BEAST_1, UNLEASHING_THE_BEAST_2, UNLEASHING_THE_BEAST_3, UNLEASHING_THE_BEAST_4, UNLEASHING_THE_BEAST_5, UNLEASHING_THE_BEAST_6, UNLEASHING_THE_BEAST_7, UNLEASHING_THE_BEAST_8]
HUNTING_FOR_TRUTH = "1-4: Hunting For Truth"
HUNTING_FOR_TRUTH_SUBREGIONS = [HUNTING_FOR_TRUTH_0, HUNTING_FOR_TRUTH_1, HUNTING_FOR_TRUTH_2, HUNTING_FOR_TRUTH_3, HUNTING_FOR_TRUTH_4, HUNTING_FOR_TRUTH_5, HUNTING_FOR_TRUTH_6, HUNTING_FOR_TRUTH_7, HUNTING_FOR_TRUTH_8]
LURKING_IN_THE_SHADOWS = "1-5: Lurking In The Shadows"
LURKING_IN_THE_SHADOWS_SUBREGIONS = [LURKING_IN_THE_SHADOWS_0, LURKING_IN_THE_SHADOWS_1, LURKING_IN_THE_SHADOWS_2, LURKING_IN_THE_SHADOWS_3, LURKING_IN_THE_SHADOWS_4, LURKING_IN_THE_SHADOWS_5, LURKING_IN_THE_SHADOWS_6, LURKING_IN_THE_SHADOWS_7, LURKING_IN_THE_SHADOWS_8]

#Oasis
